[system]

max_grad          =     30 # [mT/m]
max_slew          =    140 # [T/m/s]
grad_raster_time  =  10e-6 # [s]
rf_raster_time    =   1e-6 # [s]
rf_ringdown_time  =  10e-6 # [s]
rf_dead_time      = 200e-6 # [s]
adc_dead_time     =  10e-6 # [s]

[spiral]
contrast        = 'trueFISP'
slew_ratio   = 1.0  # How much of the system slew rate to be used for spiral design.  
ro_duration = 3e-3 # [s] Readout duration
adc_dwell   = 1e-6 # [s]
arm_ordering = 'linear' # 'linear', 'ga', 'tinyga', 'linear_custom'
GA_steps    = 144  # 0 to disable GA
GA_angle    = 111.246  # [deg]
# custom_order = [0,1,2,3,4,5,6,7,8,9] # Custom ordering of the arms determined by 0-indexed interleave number. Only enabled if arm_ordering='linear_custom'
# Note: custom_order assumes the number of interleaves, and does not work if it does not match.

[acquisition]
resolution      = 2.4       # [mm]
fov             = [24]  # [cm]
slice_thickness = 6       # [mm]

flip_angle      = 35.0
rf_duration     = 1e-3  # [s]

TR              = 0     # [ms], 0 for min TR
TE              = 0     # [ms], 0 for min TE

repetitions     = 16 

[[preparations]]
type            = "tagging"
enabled         = true 
tag_type        = "grid"
grid_tag_spacing = 2.0  # [cm]
 
[user_settings]
write_seq    = true
filename_ext = '' # This will be attached to the filename
show_plots   = true 
detailed_rep = true
